[package]
name = "ddi"
version = "0.1.0"
authors = ["tralph3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
termion = "*"